// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisChampionshipMicroservice.Adapters.SqliteAdapters;

#nullable disable

namespace TennisChampionshipMicroservice.Migrations.CourtDb
{
    [DbContext(typeof(CourtDbContext))]
    partial class CourtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("TennisChampionshipMicroservice.Models.Entities.CourtEntity", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFree")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNearGym")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNearRestaurant")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourtId");

                    b.ToTable("Courts");
                });
#pragma warning restore 612, 618
        }
    }
}
